development:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: buy_edwin_pizza_database_development

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: buy_edwin_pizza_database_production
