development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: buy_edwin_pizza_database_production
